name: Deploy
on:
  pull_request:
  push:
    branches:
      - main
  # Schedule monthly builds
  schedule:
    - cron: '0 0 1 * *'

jobs:
  Deploy:
    # Edit here if compiling multiple papers
    needs: [build]
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: public

      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
